export const BLOCK_CLASSES =
  'dice-block dice-block--comparison-table min-h-screen bg-background';

export const movers = [
  {
    id: 1,
    name: 'Bay Area Moving & Storage',
    location: 'San Francisco, CA',
    services: 'Local, Long-Distance, Packing',
    specialty: 'Residential moves',
    pricing: '$120-150/hr',
    minimum: '3-hour minimum',
    rating: 4.8,
  },
  {
    id: 2,
    name: 'Golden State Movers',
    location: 'Los Angeles, CA',
    services: 'Local, Commercial, Storage',
    specialty: 'Office relocations',
    pricing: '$110-140/hr',
    minimum: '4-hour minimum',
    rating: 4.9,
  },
  {
    id: 3,
    name: 'Pacific Coast Moving',
    location: 'San Diego, CA',
    services: 'Full-Service, Packing, Storage',
    specialty: 'Long-distance moves',
    pricing: '$3,500-5,000',
    minimum: 'flat rate',
    rating: 4.7,
  },
  {
    id: 4,
    name: 'Silicon Valley Movers',
    location: 'San Jose, CA',
    services: 'Local, Packing, Piano Moving',
    specialty: 'Apartment moves',
    pricing: '$100-130/hr',
    minimum: '2-hour minimum',
    rating: 4.9,
  },
  {
    id: 5,
    name: 'Coastal Moving Services',
    location: 'Santa Barbara, CA',
    services: 'Local, Long-Distance, Storage',
    specialty: 'Senior relocations',
    pricing: '$115-145/hr',
    minimum: '3-hour minimum',
    rating: 4.6,
  },
  {
    id: 6,
    name: 'Sacramento Pro Movers',
    location: 'Sacramento, CA',
    services: 'Local, Commercial, Packing',
    specialty: 'Same-day moves',
    pricing: '$105-135/hr',
    minimum: '3-hour minimum',
    rating: 4.8,
  },
];
